services:
  # Frontend (Vite + React) - PRODUCTION READY
  # Lightweight SPA with Nginx serving static files
  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # Backend (Flask API)
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Hot reload for development
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - SECRET_KEY=backend-secret-key-change-in-production
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped

  # Database (PostgreSQL)
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"  # Exposed for external connections (DBeaver, worker, etc.)
    networks:
      - app-network
    restart: unless-stopped

  # Message Queue (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP port for worker
      - "15672:15672" # Management UI
    networks:
      - app-network
    restart: unless-stopped

  # Grader Worker (Go implementation - production ready)
  worker:
    build:
      context: ./grader-engine-go
      dockerfile: Dockerfile
    volumes:
      - ./grader-engine-go:/app
      - ./grader-temp:/grader-temp
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for running containers
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - RABBITMQ_HOST=rabbitmq
      - BACKEND_API_URL=http://backend:5000
      - DOCKER_IMAGE=code-grader-project-sandbox:latest
      - CONTAINER_POOL_SIZE=5
      # Database connection pool settings
      - DB_MAX_IDLE_CONNS=10
      - DB_MAX_OPEN_CONNS=100
      - DB_CONN_MAX_LIFETIME_MINUTES=60
      # Logging configuration
      - LOG_LEVEL=INFO
      - LOG_FORMAT=text  # Use 'json' for production log aggregation
    depends_on:
      - postgres
      - rabbitmq
      - backend
    networks:
      - app-network
    restart: unless-stopped
    privileged: true  # Required for Docker-in-Docker

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: