"""Add Resource model for problem attachments

Revision ID: cc3f91576b4c
Revises: 751984f32e60
Create Date: 2025-11-03 04:13:56.524369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc3f91576b4c'
down_revision = '751984f32e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('drive_link', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_problem_id'), ['problem_id'], unique=False)

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.alter_column('function_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('return_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'int'::character varying"))
        batch_op.alter_column('parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.drop_index(batch_op.f('idx_problems_class_id'))
        batch_op.drop_index(batch_op.f('ix_problems_language'))
        batch_op.drop_index(batch_op.f('ix_problems_language_limits'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_problems_return_type'))
    
    # Handle parameter_types conversion separately with explicit USING clause
    op.execute('ALTER TABLE problems ALTER COLUMN parameter_types TYPE JSONB USING parameter_types::text::jsonb')

    with op.batch_alter_table('submission_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_submission_results_submission_id'))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('is_test',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_index(batch_op.f('idx_submissions_problem_id'))
        batch_op.drop_index(batch_op.f('idx_submissions_student_id'))
        batch_op.create_index(batch_op.f('ix_submissions_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_test_cases_problem_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_test_cases_problem_id'), ['problem_id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_student_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_problem_id'))
        batch_op.create_index(batch_op.f('idx_submissions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_submissions_problem_id'), ['problem_id'], unique=False)
        batch_op.alter_column('is_test',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('submission_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_submission_results_submission_id'), ['submission_id'], unique=False)

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_return_type'), ['return_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_language_limits'), ['language_limits'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_problems_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('idx_problems_class_id'), ['class_id'], unique=False)
        batch_op.alter_column('parameter_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
        batch_op.alter_column('parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('return_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'int'::character varying"))
        batch_op.alter_column('function_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_problem_id'))

    op.drop_table('resources')
    # ### end Alembic commands ###
